(defun run2 ()
  (load "day4/day4-1.lisp")
  (setf r (cl-csv:read-csv #P"day4/data4.csv"))
  (loop for c in (generate (length (CADAR r)) 1) count (if (AND (find `2 (consecutive c 1)) (inrange c r)) c))
)
